---
name: s2hub-cms-popup
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 's2hub/silverstripe-cms-popup: client/dist/js/bundle.js'
  extra_requirements_css:
    - 's2hub/silverstripe-cms-popup: client/dist/css/cms-popup.css'

SilverStripe\Control\Director:
  rules:
    'cms-search//$Action': 'S2Hub\CmsPopup\Control\CmsPopupSearchRouterController'
    'cms-batch//$Action': 'S2Hub\CmsPopup\Control\CmsPopupBatchRouterController'
